# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66afa752d40e608c17c75a3258329aecc896263c94fdf33b93dd6ab65d06ed039359f2f2c2b47fbb7d64dd3914f366d85655cecd805ac2c178f9ed9dbac3f16b

test:
  secret_key_base: b629a5e26e9f8b332486afc5478a3138b0f89e8fb0a3c3e06676a77cfe1f4ba4b2bfd54c66ae1e93790384004f8363e5c9693e0da6632580ee9124767896d074

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
